// Mocks generated by Mockito 5.4.5 from annotations
// in takmed/test/features/onboarding/presentation/bloc/onboarding_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:takmed/core/errors/failures.dart' as _i5;
import 'package:takmed/features/onboarding/domain/entities/user_track.dart'
    as _i6;
import 'package:takmed/features/onboarding/domain/usecases/complete_onboarding_use_case.dart'
    as _i8;
import 'package:takmed/features/onboarding/domain/usecases/get_track_use_case.dart'
    as _i7;
import 'package:takmed/features/onboarding/domain/usecases/save_track_use_case.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SaveTrackUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveTrackUseCase extends _i1.Mock implements _i3.SaveTrackUseCase {
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> call(_i6.UserTrack? track) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [track],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #call,
            [track],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
                _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #call,
            [track],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);
}

/// A class which mocks [GetTrackUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTrackUseCase extends _i1.Mock implements _i7.GetTrackUseCase {
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UserTrack?>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.UserTrack?>>.value(
            _FakeEither_0<_i5.Failure, _i6.UserTrack?>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.UserTrack?>>.value(
                _FakeEither_0<_i5.Failure, _i6.UserTrack?>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.UserTrack?>>);
}

/// A class which mocks [CompleteOnboardingUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCompleteOnboardingUseCase extends _i1.Mock
    implements _i8.CompleteOnboardingUseCase {
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
                _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);
}
