// Mocks generated by Mockito 5.4.5 from annotations
// in takmed/test/features/gamification/services/streak_reminder_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:takmed/core/sync/gamification_cloud_sync.dart' as _i4;
import 'package:takmed/features/gamification/data/services/i_reminder_service.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IReminderService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIReminderService extends _i1.Mock implements _i2.IReminderService {
  MockIReminderService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> areNotificationsEnabled() => (super.noSuchMethod(
        Invocation.method(
          #areNotificationsEnabled,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> scheduleDailyReminder(int? streak) => (super.noSuchMethod(
        Invocation.method(
          #scheduleDailyReminder,
          [streak],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cancelReminderForToday(int? streak) => (super.noSuchMethod(
        Invocation.method(
          #cancelReminderForToday,
          [streak],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cancelAll() => (super.noSuchMethod(
        Invocation.method(
          #cancelAll,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [GamificationCloudSync].
///
/// See the documentation for Mockito's code generation for more information.
class MockGamificationCloudSync extends _i1.Mock
    implements _i4.GamificationCloudSync {
  MockGamificationCloudSync() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> pushToCloud() => (super.noSuchMethod(
        Invocation.method(
          #pushToCloud,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> restoreFromCloud() => (super.noSuchMethod(
        Invocation.method(
          #restoreFromCloud,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
