// Mocks generated by Mockito 5.4.5 from annotations
// in takmed/test/features/ai_chat/chat_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:takmed/core/errors/failures.dart' as _i5;
import 'package:takmed/features/ai_chat/domain/entities/chat_message_entity.dart'
    as _i6;
import 'package:takmed/features/ai_chat/domain/entities/chat_send_result.dart'
    as _i8;
import 'package:takmed/features/ai_chat/domain/usecases/get_chat_history_use_case.dart'
    as _i3;
import 'package:takmed/features/ai_chat/domain/usecases/send_chat_message_use_case.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetChatHistoryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetChatHistoryUseCase extends _i1.Mock
    implements _i3.GetChatHistoryUseCase {
  MockGetChatHistoryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.ChatMessageEntity>>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.Failure, List<_i6.ChatMessageEntity>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.ChatMessageEntity>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.ChatMessageEntity>>>);
}

/// A class which mocks [SendChatMessageUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSendChatMessageUseCase extends _i1.Mock
    implements _i7.SendChatMessageUseCase {
  MockSendChatMessageUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.ChatSendResult>> call(
          _i7.SendChatMessageParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i8.ChatSendResult>>.value(
                _FakeEither_0<_i5.Failure, _i8.ChatSendResult>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i8.ChatSendResult>>);
}
